/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:702014:
  addClipboard();
} //_CODE_:button1:702014:

public void button2_click1(GButton source, GEvent event) { //_CODE_:button2:834439:
  wiewClipboard();
} //_CODE_:button2:834439:

public void button3_click1(GButton source, GEvent event) { //_CODE_:button3:832375:
  deleteClipboards();
} //_CODE_:button3:832375:

public void button4_click1(GButton source, GEvent event) { //_CODE_:button4:768668:
  credits();
} //_CODE_:button4:768668:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  button1 = new GButton(this, width/6, 149, 110, 45);
  button1.setText("Add to clipboard");
  button1.addEventHandler(this, "button1_click1");
  button2 = new GButton(this, width-(width/3), 156, 110, 45);
  button2.setText("Wiew clipboard");
  button2.addEventHandler(this, "button2_click1");
  button3 = new GButton(this, width/6, 241, 110, 45);
  button3.setText("Delete all clipboards");
  button3.addEventHandler(this, "button3_click1");
  button4 = new GButton(this, width-(width/3), 239, 110, 45);
  button4.setText("Credits");
  button4.addEventHandler(this, "button4_click1");
}

// Variable declarations 
// autogenerated do not edit
GButton button1; 
GButton button2; 
GButton button3; 
GButton button4; 
